# Generated by Django 4.2 on 2025-03-24 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=20)),
                ('publisher', models.CharField(max_length=50)),
                ('publish_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=20)),
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bookinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ucl_email', models.CharField(max_length=50)),
                ('credit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Borrows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('returned_date', models.DateField(null=True)),
                ('book_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bookitem')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.person')),
            ],
        ),
    ]
