# Generated by Django 5.1.2 on 2025-03-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bookinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrows',
            name='returned_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
